services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 5432
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
     - postgres-data:/var/lib/postgresql/data
    networks:
      - initexample
  backend:
    build:
      context: ./salade-tomates-oignons-back
      dockerfile: ./Dockerfile
    expose:
      - 8080
    ports:
        - "8080:8080"
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    restart: unless-stopped
    networks:
      - initexample
  frontend:
    build:
      context: ./salade-tomates-oignons-front
      dockerfile: ./Dockerfile
    expose:
      - 4200
    ports:
        - "4200:4200"
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - initexample
volumes:
  postgres-data:

networks:
  initexample:
    driver: bridge